### PR TITLE
fix: navbar layout

### PR DESCRIPTION
**Pull request by amanzrx4**
hi, i've fixed some changes in the navbar, rn if you go to devices and then homepage page again, the mobile menu doesnt appear on clicking hamburger btn, may be because you're loading the standalone script in the render method of navbar component, ive fixed it with useState and also, the download btn on navbar wasnt cursor-pointer so fixed that too :)

### CODE REVIEW

**Review by rxri — CHANGES_REQUESTED** [review]
Hi, thanks for pr.
Please remove package-lock.json since we don't use `npm` in this repo but `yarn v2` instead.
Also I don't think `@types/node` is necessary in frontend repo?

**Comment by amanzrx4** [comment]
hi, i've made the changes

**Comment by rxri** [comment]
I forgot to say, can you update yarn.lock by running just "yarn" command?

**Comment by amanzrx4** [comment]
yes done

**Pull request merged**
